---
- name: Ensure Pip is installed.
  stat: path=/usr/bin/pip
  register: pip_binary

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ pip_packages }}"
  when: pip_binary.stat.exists
